# pandas.DataFrame - 1

In [1]:
import numpy as np
import pandas as pd
import sys
print(sys.platform, sys.version, f'numpy version {np.__version__}',  f'pandas version {pd.__version__}',sep='\n')

win32
3.14.2 (tags/v3.14.2:df79316, Dec  5 2025, 17:18:21) [MSC v.1944 64 bit (AMD64)]
numpy version 2.4.1
pandas version 3.0.0

### Створення

Створення за масивом <code>np.ndarray</code>

In [2]:
arr = np.array(range(1, 17)).reshape(4, 4)
d = pd.DataFrame(arr)
d

    0   1   2   3
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16

Створення за сукупністю <code>Series</code>

In [3]:
s1 = pd.Series([1, 2, 3], index=list('abc'), dtype=int)
s1

a    1
b    2
c    3
dtype: int64

In [4]:
s2 = pd.Series([4, 5, 7], index=list('abd'), dtype=int, name='v2')
s2

a    4
b    5
d    7
Name: v2, dtype: int64

In [5]:
d = pd.DataFrame({'v1':s1, 'v2':s2})
d

    v1   v2
a  1.0  4.0
b  2.0  5.0
c  3.0  NaN
d  NaN  7.0

Зверніть увагу, що стовпчики таблиці мають спільний індекс. Через те, що було необхідно мати незаповнені клітини, змінився тип даних стовпчиків.

Створення за об'єктом <code>Series</code>

In [6]:
pd.DataFrame(s1)

   0
a  1
b  2
c  3

In [7]:
pd.DataFrame(s2)

   v2
a   4
b   5
d   7

Створення за словником зі значеннями-послідовностями

In [8]:
import random
n = 10
ids = [f'var {i}' for i in range(1, n+1)]
v1 = [random.randint(0, 9) for _ in range(n)]
v2 = [random.randint(10, 19) for _ in range(n)]
v3 = (random.randint(20, 29) for _ in range(n))
raw_data = {'id':ids, 'v1':v1, 'v3':v3, 'v2':v2}
data = pd.DataFrame(raw_data)
orig = data.copy()
data.head()

      id  v1  v3  v2
0  var 1   7  20  15
1  var 2   9  23  13
2  var 3   4  28  15
3  var 4   4  20  17
4  var 5   8  29  11

In [9]:
data.size

40

In [10]:
data.shape

(10, 4)

In [11]:
len(data)

10

In [12]:
data.dtypes

id      str
v1    int64
v3    int64
v2    int64
dtype: object

In [13]:
data.axes

[RangeIndex(start=0, stop=10, step=1),
 Index(['id', 'v1', 'v3', 'v2'], dtype='str')]

In [14]:
data.index

RangeIndex(start=0, stop=10, step=1)

In [15]:
data.columns

Index(['id', 'v1', 'v3', 'v2'], dtype='str')

### Перегляд даних нашвидкоруч

In [16]:
data.head()

      id  v1  v3  v2
0  var 1   7  20  15
1  var 2   9  23  13
2  var 3   4  28  15
3  var 4   4  20  17
4  var 5   8  29  11

In [17]:
data.tail(3)

       id  v1  v3  v2
7   var 8   3  27  13
8   var 9   8  26  17
9  var 10   6  22  19

In [18]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      10 non-null     str
 1   v1      10 non-null     int64
 2   v3      10 non-null     int64
 3   v2      10 non-null     int64
dtypes: int64(3), str(1)
memory usage: 452.0 bytes

In [19]:
data.describe()

              v1         v3         v2
count  10.000000  10.000000  10.000000
mean    5.300000  23.700000  15.400000
std     2.668749   3.497618   2.503331
min     1.000000  20.000000  11.000000
25%     3.250000  20.500000  13.500000
50%     5.000000  22.500000  15.500000
75%     7.750000  26.750000  17.000000
max     9.000000  29.000000  19.000000

## Доступ до даних

Отримання стовпчиків таблиці

In [20]:
data['id']

0     var 1
1     var 2
2     var 3
3     var 4
4     var 5
5     var 6
6     var 7
7     var 8
8     var 9
9    var 10
Name: id, dtype: str

In [21]:
data.id

0     var 1
1     var 2
2     var 3
3     var 4
4     var 5
5     var 6
6     var 7
7     var 8
8     var 9
9    var 10
Name: id, dtype: str

In [22]:
# data['id'][3] = 'www'    # так не треба! ніколи
# data.id[3]='www'         # і так також! ніколи

Вибірка стовпчиків таблиці

In [23]:
data[['id']]

       id
0   var 1
1   var 2
2   var 3
3   var 4
4   var 5
5   var 6
6   var 7
7   var 8
8   var 9
9  var 10

In [24]:
data[['id', 'v1']]

       id  v1
0   var 1   7
1   var 2   9
2   var 3   4
3   var 4   4
4   var 5   8
5   var 6   3
6   var 7   1
7   var 8   3
8   var 9   8
9  var 10   6

Доступ до даних

In [25]:
data.head(3)

      id  v1  v3  v2
0  var 1   7  20  15
1  var 2   9  23  13
2  var 3   4  28  15

In [26]:
data.at[0, 'v1']

np.int64(7)

In [27]:
data.iat[2, 1]

np.int64(4)

In [28]:
data.loc[0,'v3']

np.int64(20)

In [29]:
data.iloc[0, 3]

np.int64(15)

In [30]:
data.loc[0:2, 'v1':'v3']

   v1  v3
0   7  20
1   9  23
2   4  28

In [31]:
data.iloc[0:3, 1:3]

   v1  v3
0   7  20
1   9  23
2   4  28

In [32]:
data.iloc[0:3, 1:3] += 3
data.iloc[0:3, 1:3]

   v1  v3
0  10  23
1  12  26
2   7  31

In [33]:
data.loc[0:2, ('v1', 'v2', 'v3')]

   v1  v2  v3
0  10  15  23
1  12  13  26
2   7  15  31

In [34]:
data.iloc[0:3, [2, 1]]

   v3  v1
0  23  10
1  26  12
2  31   7

In [35]:
data.iloc[0:3, 1] = 33
data

       id  v1  v3  v2
0   var 1  33  23  15
1   var 2  33  26  13
2   var 3  33  31  15
3   var 4   4  20  17
4   var 5   8  29  11
5   var 6   3  22  18
6   var 7   1  20  16
7   var 8   3  27  13
8   var 9   8  26  17
9  var 10   6  22  19

### Перетворення

<b>Переупорядкування стовпчиків, зміна індексу</b>

In [36]:
data = data.reindex(columns=('id', 'v1', 'v2', 'v3'))  # copy = True by default
data.head(2)

      id  v1  v2  v3
0  var 1  33  15  23
1  var 2  33  13  26

In [37]:
data.set_index('id', inplace=True)
data.head(2)

       v1  v2  v3
id
var 1  33  15  23
var 2  33  13  26

In [38]:
data.reset_index(inplace=True)
data.head(2)

      id  v1  v2  v3
0  var 1  33  15  23
1  var 2  33  13  26

<b>Додавання та вилучення стовпчиків</b>

In [39]:
data['v4'] = data.v1 + data.v2
data.head(3)

      id  v1  v2  v3  v4
0  var 1  33  15  23  48
1  var 2  33  13  26  46
2  var 3  33  15  31  48

In [40]:
# del data['v4']
data.drop(columns='v4', inplace=True)
data.head(3)

      id  v1  v2  v3
0  var 1  33  15  23
1  var 2  33  13  26
2  var 3  33  15  31

In [41]:
data['x'] = 0
data['y'] = 0
data.head(2)

      id  v1  v2  v3  x  y
0  var 1  33  15  23  0  0
1  var 2  33  13  26  0  0

In [42]:
data.drop(columns=['x', 'y'], inplace=True)
data.head(3)

      id  v1  v2  v3
0  var 1  33  15  23
1  var 2  33  13  26
2  var 3  33  15  31

<b>Сортування даних</b>

In [43]:
data['total'] = data['v1']+data['v2']+data['v3']
data.head(5)

      id  v1  v2  v3  total
0  var 1  33  15  23     71
1  var 2  33  13  26     72
2  var 3  33  15  31     79
3  var 4   4  17  20     41
4  var 5   8  11  29     48

In [44]:
data.sort_values(by=['total', 'id'], ascending=[False, True], inplace=True)
data

       id  v1  v2  v3  total
2   var 3  33  15  31     79
1   var 2  33  13  26     72
0   var 1  33  15  23     71
8   var 9   8  17  26     51
4   var 5   8  11  29     48
9  var 10   6  19  22     47
5   var 6   3  18  22     43
7   var 8   3  13  27     43
3   var 4   4  17  20     41
6   var 7   1  16  20     37

In [45]:
data.index

Index([2, 1, 0, 8, 4, 9, 5, 7, 3, 6], dtype='int64')

In [46]:
data.sort_index(inplace=True)
data

       id  v1  v2  v3  total
0   var 1  33  15  23     71
1   var 2  33  13  26     72
2   var 3  33  15  31     79
3   var 4   4  17  20     41
4   var 5   8  11  29     48
5   var 6   3  18  22     43
6   var 7   1  16  20     37
7   var 8   3  13  27     43
8   var 9   8  17  26     51
9  var 10   6  19  22     47

### Вибірки даних

In [47]:
(data['v1'] >= 3)  # можна і data.v1, і data['v1']

0     True
1     True
2     True
3     True
4     True
5     True
6    False
7     True
8     True
9     True
Name: v1, dtype: bool

In [48]:
(data['v1'] >= 3) & (data['v3'] > 22)

0     True
1     True
2     True
3    False
4     True
5    False
6    False
7     True
8     True
9    False
dtype: bool

In [49]:
np.logical_and((data['v1'] >= 3), (data['v3'] > 22))

0     True
1     True
2     True
3    False
4     True
5    False
6    False
7     True
8     True
9    False
dtype: bool

In [50]:
data[(data['v1'] >= 3) & (data['v3'] > 22)]

      id  v1  v2  v3  total
0  var 1  33  15  23     71
1  var 2  33  13  26     72
2  var 3  33  15  31     79
4  var 5   8  11  29     48
7  var 8   3  13  27     43
8  var 9   8  17  26     51

In [51]:
data[(data['v1']<3) | (data['v3']==20)]

      id  v1  v2  v3  total
3  var 4   4  17  20     41
6  var 7   1  16  20     37

### Обходи

In [52]:
for el in data:
    print(el)

id
v1
v2
v3
total

In [53]:
for el in data.itertuples():
    print(el)

Pandas(Index=0, id='var 1', v1=33, v2=15, v3=23, total=71)
Pandas(Index=1, id='var 2', v1=33, v2=13, v3=26, total=72)
Pandas(Index=2, id='var 3', v1=33, v2=15, v3=31, total=79)
Pandas(Index=3, id='var 4', v1=4, v2=17, v3=20, total=41)
Pandas(Index=4, id='var 5', v1=8, v2=11, v3=29, total=48)
Pandas(Index=5, id='var 6', v1=3, v2=18, v3=22, total=43)
Pandas(Index=6, id='var 7', v1=1, v2=16, v3=20, total=37)
Pandas(Index=7, id='var 8', v1=3, v2=13, v3=27, total=43)
Pandas(Index=8, id='var 9', v1=8, v2=17, v3=26, total=51)
Pandas(Index=9, id='var 10', v1=6, v2=19, v3=22, total=47)

In [54]:
el.Index

9

In [55]:
el.v3

22

In [56]:
el[4]

22

In [57]:
for el in data.itertuples(index=False, name=None):
    print(el)

('var 1', 33, 15, 23, 71)
('var 2', 33, 13, 26, 72)
('var 3', 33, 15, 31, 79)
('var 4', 4, 17, 20, 41)
('var 5', 8, 11, 29, 48)
('var 6', 3, 18, 22, 43)
('var 7', 1, 16, 20, 37)
('var 8', 3, 13, 27, 43)
('var 9', 8, 17, 26, 51)
('var 10', 6, 19, 22, 47)