# pandas.DataFrame: Робота з рядковими значеннями

In [1]:
import numpy as np
import pandas as pd
import sys
print(sys.platform, sys.version, f'numpy version {np.__version__}',  f'pandas version {pd.__version__}',sep='\n')

win32
3.14.2 (tags/v3.14.2:df79316, Dec  5 2025, 17:18:21) [MSC v.1944 64 bit (AMD64)]
numpy version 2.4.1
pandas version 3.0.0

Складемо таблицю <code>data</code> з рядковими даними. Оскільки далі над нею будуть виконуватись різноманітні перетворення, то створимо її копію у змінній <code>orig</code>, щоб не повторювати процес створення.

In [2]:
import random
n = 10
ids = [f'var {i}' for i in range(1, n+1)]
v1 = [random.randint(0, 9) for _ in range(n)]
v2 = [random.randint(10, 19) for _ in range(n)]
v3 = (random.randint(20, 29) for _ in range(n))
raw_data = {'id':ids, 'v1':v1, 'v2':v2, 'v3':v3}
data = pd.DataFrame(raw_data)
orig = data.copy()
data.head()

      id  v1  v2  v3
0  var 1   9  11  21
1  var 2   7  18  23
2  var 3   3  13  24
3  var 4   5  13  23
4  var 5   0  13  29

Стовпчик <code>id</code> таблиці містить рядкові дані, що позначають номери варіантів.

In [3]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      10 non-null     str
 1   v1      10 non-null     int64
 2   v2      10 non-null     int64
 3   v3      10 non-null     int64
dtypes: int64(3), str(1)
memory usage: 452.0 bytes

Відсортуємо таблицю за значеннями стовпчика  <code>id</code>.

In [4]:
data.sort_values('id', inplace=True)
data.head(3)

       id  v1  v2  v3
0   var 1   9  11  21
9  var 10   6  15  29
1   var 2   7  18  23

Оскільки значеннями є рядки, то сортування виконано в лексикографічному порядку. Це не зовсім влаштовує, адже <code>var 10</code> має розміщуватися після <code>var 9</code>, а не після <code>var 1</code>.

Отримане сортування обумовлено саме тим, що сортувалися рядкові дані.

Щоб отримати сортування за номерами варіантів, необхідно виконати перетворення. Наприклад, побудувати числовий стовпчик з номерами варіантів.

Проведемо попередні дослідження цього питання.

In [5]:
data.id.str.findall(r'[var]')  # v|a|r DM: v+a+r  [a-z]  [^abc] [a-zA-Z]

0    [v, a, r]
9    [v, a, r]
1    [v, a, r]
2    [v, a, r]
3    [v, a, r]
4    [v, a, r]
5    [v, a, r]
6    [v, a, r]
7    [v, a, r]
8    [v, a, r]
Name: id, dtype: object

In [6]:
data.id.str.findall(r'(\s*(var)\s*(\d+)\s*)')   #\s  \d # [abc]+  [0-9]    a|ab

0      [(var 1, var, 1)]
9    [(var 10, var, 10)]
1      [(var 2, var, 2)]
2      [(var 3, var, 3)]
3      [(var 4, var, 4)]
4      [(var 5, var, 5)]
5      [(var 6, var, 6)]
6      [(var 7, var, 7)]
7      [(var 8, var, 8)]
8      [(var 9, var, 9)]
Name: id, dtype: object

In [7]:
data.id.str.findall(r'\s*var\s*(\d+)\s*').str[0]

0     1
9    10
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
Name: id, dtype: object

In [8]:
data.id.str.match(r'\s*var\s*\d+\s*')

0    True
9    True
1    True
2    True
3    True
4    True
5    True
6    True
7    True
8    True
Name: id, dtype: bool

In [9]:
#import re
#r1 = re.compile(r'\s*var\s*(\d+)\s*')
#def f(s, r1):
#    res = re.fullmatch(r1, s)
#    return res[1]

#data.id.apply(f, args=(r1,))

In [10]:
data.id = data.id.str.findall(r'\s*var\s*(\d+)\s*').str[0]
data.head()

   id  v1  v2  v3
0   1   9  11  21
9  10   6  15  29
1   2   7  18  23
2   3   3  13  24
3   4   5  13  23

In [11]:
data.sort_values(by='id', inplace=True)
data.head()

   id  v1  v2  v3
0   1   9  11  21
9  10   6  15  29
1   2   7  18  23
2   3   3  13  24
3   4   5  13  23

In [12]:
data.info()

<class 'pandas.DataFrame'>
Index: 10 entries, 0 to 8
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      10 non-null     object
 1   v1      10 non-null     int64
 2   v2      10 non-null     int64
 3   v3      10 non-null     int64
dtypes: int64(3), object(1)
memory usage: 400.0+ bytes

In [13]:
data.id = data.id.astype('int64')
data.sort_values(by='id', inplace=True)
data.head()

   id  v1  v2  v3
0   1   9  11  21
1   2   7  18  23
2   3   3  13  24
3   4   5  13  23
4   5   0  13  29

In [14]:
data.tail()

   id  v1  v2  v3
5   6   9  19  23
6   7   5  17  24
7   8   2  10  24
8   9   1  12  21
9  10   6  15  29

Документація на метод <code>findall</code> тут <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.str.findall.html" target=_blank rel="noopener noreferrer"><code>Series.str.findall</code></a>.

Більше операцій, що можуть виконуватись над рядками, дивись у документації. Відповідні методи в документації адресуються як <code>Series.str.назва_методу</code>.