# LAB2 Частина 2. Оброблення даних про файли

Виконавець:  <b>впишіть власне ПІБ</b>, група <b>впишіть власну групу</b>
<br> Викладач: <b>впишіть хто веде лабораторні заняття</b>

Нам знадобиться бібліотека <code>pandas</code>.
<br>
Бібліотека є сторонньою, отже потребує встановлення. Краще у віртуальне оточення. 
<br>
Мала бути встановлена, якщо ні (клітина з імпортуванням виконується з помилкою), то треба встановити. Можна прямо з Jupyter. Тільки не під час пари. 

<b>Наступну клітину можна розкоментовувати та виконувати тільки, якщо в якості ядра (kernel) вибране віртуальне оточення!</b>

In [1]:
#!pip install pandas

Якщо встановлювати не в оточення, то хоча б тільки для користувача (з ключем --user).

In [2]:
#!pip3.14 install pandas --user    # Linux

In [3]:
#!py -3.14 -m pip install pandas --user    # Windows

In [1]:
from pathlib import Path
import pandas as pd
print(f'pandas {pd.__version__}')

pandas 3.0.0

### Постановка задачі

<u>Згадка про минуле (Лабораторну роботу №1)</u>
<br>Протягом навчання програмні проєкти з різних предметів зберігалися в папках з переліку <code>folders</code>, який оброблявся в лабораторній роботі&nbsp;№1.
<br>
Щоб профільтрувати допоміжні файли середовищ, було введено "білий список" розширень (<code>WHITE_LIST</code>) та список розширень файлів з текстом програм(задається) (<code>CODE_LIST</code>).
<br>
Також було написано функцію <code>kind</code>, що за розширенням повертає рядок з символом C,W або O відповідно для файлів з текстом програм (відповідно до переліку <code>CODE_LIST</code>), інших з білого списку, та тих, що не потрапили в білий список).

У результаті виконання лабораторної роботи  для кожного місяця та кожного розширення, що зустрічаються при перегляді файлів, розміщених у папках зі списку, було знайдено таку інформацію:

    рік, місяць, розширення, кількість файлів, сумарний обсяг у байтах, кількість їх рядків.
    
Кількість рядків наводиться тільки для розширень категорії C; білі та порожні рядки не рахуються; для інших розширень ця клітина таблиці залишається незаповненою.

За цією інформацією було побудовано csv-файл з іменем <code>lab1_1.csv</code> (кодування тільки utf-8), на початку якого розміщено рядок з заголовками: year, mon, ext, cnt, size, lines.

In [1]:
CODE_LIST = {'.cpp', '.hpp', '.c', '.h', '.py', '.pyw', '.cs', '.js', '.java'}
WHITE_LIST = CODE_LIST | {'.html', '.json', '.txt', '.ipynb'}

In [2]:
headers = ['year', 'mon', 'ext', 'cnt', 'size', 'lines']

<b>За інформацією з csv-файлу</b> з'ясувати

<ol>
    <li>Скільки різних розширень зустрічається у папках з заданого списку, скільки файлів з кожним розширенням.
    (Для цієї задачі розглядаємо всі розширення, а не тільки "білого списку".)</li>    
    Відповідну інформацію вивести на екран у табличному вигляді. Рядки таблиці містять розширення, кількість файлів та ознаку (C,W,O відповідно для файлів з текстом програм (розширення з списку <code>CODE_LIST</code>), інших з білого списку, та тих, що не потрапили в білий список). Інформація подається за спаданням кількості файлів. 

<li>За датами створення файлів для кожного місяця, починаючи з вересня 2024-го року, знайти таку інформацію:
    кількість файлів з розширеннями з "білого списку", їх сумарний розмір у кілобайтах, кількість їх рядків (враховувати тільки для файлів категорії C), середній розмір у байтах, середню кількість рядків.</li>
    Відповідну інформацію вивести на екран у табличному вигляді в <u>порядку, оберненому до хронологічного</u>.
</ol>

Зверніть увагу на підписи стовпчиків, що будуть виводитись.

<u>Всі значення округлити та привести до цілого типу.</u>

### Завантаження даних

Задаємо шлях до файлу <code>lab1_1.csv</code>.

In [7]:
path = Path(задати власний шлях)

Завантажимо дані за допомогою функції <code>pd.read_csv</code> (<a href="https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html#pandas-read-csv" target=_blank rel="noopener noreferrer">документація тут</a>).

Зверніть увагу на те, що:
<ol>
    <li>файл записано в кодуванні <code>utf-8<code></li>
    <li>перший рядок файлу містить заголовки year, mon, ext, cnt, size, lines</li>
    <li>значення у стовпчику <code>lines</code> можуть бути відсутні</li>
</ol>
    
<details>
    <summary>Підказки.</summary>
    Функції варто передати параметри, що задають:
    <ol>
    <li>кодування, в якому записано текстовий файл</li>
    <li>номер рядка, в якому записано заголовки</li>
    <li>тип, в якому слід записати в пам'ять останній стовпчик</li>
</ol>
</details>

<details>
    <summary>Ще більше підказок</summary>
    <ol>
    <li>параметр <code>sep</code> задає роздільники полів</li>
    <li>параметр <code>encoding</code> задає кодування</li>
    <li>параметр <code>header</code> задає номер рядка, в якому записано заголовки (нумерація починається з 0)</li>
    <li>параметр <code>dtype</code> може бути словником, що задає типи стовпчиків (можливо, не всіх); назві стовпчика відповідає назва типу</li>
    <li>тип <code>Int64</code> містить цілі числа та особливе значення <code>NA</code></li>
</ol>
</details>

In [8]:
data = pd.read_csv(записати аргументи
                  )
data.head(3)

   year  mon   ext  cnt   size  lines
0  2021   12   NaN    2   3422   <NA>
1  2021   12  .bas    2   7979   <NA>
2  2021   12  .bat  294  85220   <NA>

In [9]:
data.tail(3)

      year  mon    ext  cnt        size  lines
1021  2026    2  .xlsx   14      293131   <NA>
1022  2026    2  .yaml   18     2025769   <NA>
1023  2026    2   .zip    4  2240635049   <NA>

Подивимось інформацію про завантажені дані.
Документація на метод <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.info.html" target=_blank rel="noopener noreferrer"><code>info</code></a>.

In [10]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1024 entries, 0 to 1023
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   year    1024 non-null   int64
 1   mon     1024 non-null   int64
 2   ext     989 non-null    str
 3   cnt     1024 non-null   int64
 4   size    1024 non-null   int64
 5   lines   94 non-null     Int64
dtypes: Int64(1), int64(4), str(1)
memory usage: 49.1 KB

Бачимо, що відсутні значення є не тільки в стовпчику <code>lines</code>, що природньо, бо кількість рядків обчислювалась не для всіх розширень, але і в стовпчику <code>ext</code> з розширеннями. 

Замінимо відсутні розширення порожнім рядком.

Використаємо метод <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.fillna.html" target=_blank rel="noopener noreferrer"><code>fillna</code></a>.

Слід замінити тільки відсутні розширення, тому значення параметра <code>value</code> слід зробити словником, що для кожного стовпчика, який слід оброблювати, задає значення-заповнювач.
<br>
Не забудьте, що перетворення слід виконувати "на місці".

<details>
    <summary>Підказка (тільки за повного безвихіддя)</summary>
    <code>data.fillna(value={'ext':''}, inplace=True)</code>
</details>

<br>
<u>Альтернатива</u>. Можна спробувати перетворити тільки стовпчик <code>data.ext</code>.
<details>
    <summary>Підказка (тільки за повного безвихіддя)</summary>
    Використаємо метод <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.fillna.html#pandas.Series.fillna" target=_blank rel="noopener noreferrer"><code>fillna</code></a> класу <code>Series</code>, щоб виконати заміну, і присвоїмо результат стовпчику <code>data.ext</code>.
        <code>data.ext = data.ext.fillna(value='')</code>
</details>

<br>
Перший спосіб більш економний за пам'яттю. Другий спосіб корисний тоді, коли для різних стовпчиків використовують різні алгоритми заповнення відсутніх значень.

In [11]:
data.fillna(записати аргументи)
data.head(3)

   year  mon   ext  cnt   size  lines
0  2021   12          2   3422   <NA>
1  2021   12  .bas    2   7979   <NA>
2  2021   12  .bat  294  85220   <NA>

In [12]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1024 entries, 0 to 1023
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   year    1024 non-null   int64
 1   mon     1024 non-null   int64
 2   ext     1024 non-null   str
 3   cnt     1024 non-null   int64
 4   size    1024 non-null   int64
 5   lines   94 non-null     Int64
dtypes: Int64(1), int64(4), str(1)
memory usage: 49.1 KB

Тепер незаповнені дані залишились тільки у стовпчику <code>lines</lines>.

Ні в якому разі там не повинно бути нулів!

### Групування та групові операції

In [13]:
data.head()

   year  mon   ext  cnt    size  lines
0  2021   12          2    3422   <NA>
1  2021   12  .bas    2    7979   <NA>
2  2021   12  .bat  294   85220   <NA>
3  2021   12    .c    1    4402    141
4  2021   12  .cbp  105  172765   <NA>

<b>Задача 1</b>
Скільки різних розширень зустрічається в папках з заданого списку, скільки файлів з кожним розширенням?

Відповідну інформацію вивести на екран у табличному вигляді. Рядки таблиці містять розширення, кількість файлів та ознаку (C,W,O відповідно для файлів з текстом програм (розширення з списку <code>CODE_LIST</code>), інших з білого списку, та тих, що не потрапили в білий список). Інформація подається за спаданням кількості файлів.

##### Скільки різних розширень зустрічається в папках з заданого списку?

Найпростіше: взяти стовпчик таблиці, що зберігає розширення, та знайти кількість унікальних значень.

<details>
    <summary>Підказки</summary>
    <ol>
        <li>Для отримання стовпчика таблиці <code>t</code> з іменем <code>name</code> можна використати вираз <code>t.name</code> або <code>t['name']</code></li>
        <li>Кількість унікальних елементів ряду можна знайти за допомогою методу <code>nunique</code> 
(<a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.nunique.html" target=_blank rel="noopener noreferrer">докуемнтаці тут</a>). </li>
    </ol>
</details>

In [15]:
записати_вираз

284

##### Скільки файлів з кожним розширенням?

Відповідну інформацію вивести на екран у табличному вигляді. Рядки таблиці містять розширення, кількість файлів та ознаку (C,W,O відповідно для файлів з текстом програм (розширення з списку <code>CODE_LIST</code>), інших з білого списку, та тих, що не потрапили в білий список). Інформація подається за спаданням кількості файлів.

Спочатку треба підсумувати інформацію по кожному розширенню. Допоможе метод <code>groupby</code>  <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.groupby.html#pandas.DataFrame.groupby" target=_blank rel="noopener noreferrer">документація тут</a>.

Групувати слід за розширенням (параметр <code>by</code>) і для кожної групи обчислити суму кількостей файлів (метод <code>sum</code>).

Щоб не сумувати роки, місяці тощо, групування слід застосувати до вибірки потрібних стовпчиків. Маємо вибрати стовпчик, за яким групуємо, і стовпчик, який сумуємо.

<details>
    <summary>Підказка</summary>
    Щоб вибрати потрібні стовпчики, можна використати операцію індексації по сукупності стовпчиків, наприклад, <code>dataFrame[['columnA','columnB']]</code>
</details>

Результат присвоїти змінній <code>task1</code>.

In [16]:
task1  = записати_вираз
task1

         cnt
ext
       77311
.0        17
.1         4
.14        2
.17        2
...      ...
.xrc       2
.yaml     76
.yml     142
.zi        2
.zip      17

[284 rows x 1 columns]

Відсортувати за спаданням кількості файлів. Допоможе метод <code>sort_values</code>  (<a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sort_values.html" target=_blank rel="noopener noreferrer">документація тут</a>).

Не забудьте вказати, що сортування відбувається за спаданням та "на місці".

<details>
    <summary>Підказки</summary>
    <ol>
        <li>параметр <code>by</code> може задавати по яких стовпчиках сортувати</li>
        <li>параметр <code>ascending</code> задає спадання-зростання</li>
        <li>параметр <code>inplace</code> задає чи виконується перетворення на місці або створюється копія</li>
    </ol>
</details>

In [17]:
task1.sort_values(записати аргументи)
task1.head(3)

          cnt
ext
.meta  111220
.png    84997
        77311

За умовою ще треба додати стовпчик з ознакою категорії розширення файлу W,C,O (див. умову).
У лабораторній роботі №1 була написана функція <code>kind</code>, що за розширенням повертає рядок з шуканою ознакою. Використаємо її.

In [18]:
def kind(extension):   # записати
    pass

Додамо до таблиці стовпчик з ознаками розширень файлів.

Зараз розширення є індексом. За допомогою методу метод <code>reset_index</code>  (<a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.reset_index.html" target=_blank rel="noopener noreferrer">документація тут</a>) 
зробимо його стовпчиком таблиці. 

Не забувайте виконувати перетворення "на місці".

In [19]:
задати перетворення таблиці
task1.head(3)

     ext     cnt
0  .meta  111220
1   .png   84997
2          77311

Тепер вже додаємо стовпчик з ознаками.
<details>
    <summary>Підказки</summary>
    <ol>
        <li>Щоб додати до таблиці <code>t</code> стовпчик <code>name</code>, можна виконати присвоювання виразу <code>t['name']</code></li>
        <li>Присвоювати можна скаляр (не наш випадок) або інший стовпчик.</li>
        <li>Щоб отримати стовпчик з ознаками, можна застосувати метод <code>apply</code>  (<a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.apply.html#pandas.Series.apply" target=_blank rel="noopener noreferrer">документація тут</a>) до стовпчика з розширеннями.</li>
    </ol>
</details>

In [20]:
задати додавання стовпчика
task1.head(3)

     ext     cnt kind
0  .meta  111220    O
1   .png   84997    O
2          77311    O

За допомогою методу <code>set_index</code>  (<a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.set_index.html" target=_blank rel="noopener noreferrer">документація тут</a>) 
знов зробимо розширення індексом таблиці. 

Тут: Значенням параметра <code>keys</code> має стати ім'я стовпчика, що слід використати як індекс.

Не забувайте виконувати перетворення "на місці".

In [21]:
задати встановлення індексу
task1.head(3)

          cnt kind
ext
.meta  111220    O
.png    84997    O
        77311    O

Змінимо написи.

In [22]:
task1.index.name='Розширення'
task1.columns=['Кількість файлів','Ознака']
task1.head()

            Кількість файлів Ознака
Розширення
.meta                 111220      O
.png                   84997      O
                       77311      O
.cs                    70314      W
.py                    47833      W

In [23]:
task1.head(20)

            Кількість файлів Ознака
Розширення
.meta                 111220      O
.png                   84997      O
                       77311      O
.cs                    70314      W
.py                    47833      W
.pyc                   16264      O
.txt                   11587      W
.md                    10759      O
.tex                    6362      O
.pyi                    4451      O
.json                   3220      W
.mvfrm                  2997      O
.dll                    2950      O
.bin                    2620      O
.dat                    2192      O
.js                     1696      W
.pdb                    1631      O
.rsp                    1542      O
.asmdef                 1508      O
.mat                    1326      O

<b>Задача 2</b> За датами створення файлів для кожного місяця знайти таку інформацію:
    кількість файлів з розширеннями з "білого списку", їх сумарний розмір у кілобайтах, кількість їх рядків (враховувати тільки для файлів категорії C), середній розмір у байтах, середню кількість рядків.
    
Відповідну інформацію вивести на екран у табличному вигляді в <u>порядку, оберненому до хронологічного</u>.

<u>Всі значення округлити та привести до цілого типу.</u>

План:
<ol>
    <li>Додати до початкової таблиці <code>data</code> стовпчик <code>kind</code>, що містить ознаки розширень.</li>
    <li>Вибрати дані, що стосуються розширень з "білого списку".</li>
    <li>Згрупувати вибрані дані в межах року та місяця.</li>
    <li>За згрупованою інформацією обчислити потрібні агрегати.</li>
    <li>Виконати перетворення стовпчиків та відсортувати.</li>
</ol>

Щоб за невдачі повторно не завантажувати дані, створимо їх копію.

In [24]:
data1 = data.copy()

1. Додати до початкової таблиці <code>data</code> стовпчик <code>kind</code>, що містить ознаки розширень.

Аналогічно тому, що виконувалось раніше, додати до таблиці <code>data1</code> стовпчик <code>kind</code>, що містить ознаки.

In [25]:
задати додавання стовпчика
data1.head(3)

   year  mon   ext  cnt   size  lines kind
0  2021   12          2   3422   <NA>    O
1  2021   12  .bas    2   7979   <NA>    O
2  2021   12  .bat  294  85220   <NA>    O

2. Вибрати дані, що стосуються розширень з "білого списку".

Запишіть вираз, що задає вибірку тільки інформації про розширення з "білого списку". 
Щоб далі не копіювати сам вираз, присвойте його значення змінній <code>selection</code>. ( Це є зручно, коли експериментуємо, у продакшн потреби в цій змінній насправді не буде, замість неї можна буде використовувати вираз безпосередньо.)

<details>
    <summary>Підказка</summary>
    <ul>
    <li>Розширення знаходиться в білому списку, якщо його ознакою є не O.</li>
    <li>Обчислити умову, що розширення знаходиться в білому списку, і використати її як аргумент операції індексації.</li>
    </ul>
</details>

In [26]:
selection = записати_вираз
selection.head()

   year  mon   ext  cnt    size  lines kind
0  2021   12          2    3422   <NA>    O
1  2021   12  .bas    2    7979   <NA>    O
2  2021   12  .bat  294   85220   <NA>    O
3  2021   12    .c    1    4402    141    W
4  2021   12  .cbp  105  172765   <NA>    O

3. Згрупувати вибрані дані за ознаками в межах року та місяця.
   
   Допоможе метод <code>groupby</code>  <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.groupby.html#pandas.DataFrame.groupby" target=_blank rel="noopener noreferrer">документація тут</a>.

Групувати слід за роком та місяцем (параметр <code>by</code> має бути списком). Оскільки далі будемо обчислювати статистики для розміру та кількості рядків, то перед групуванням з таблиці слід вибрати стовпчики, за якими групуємо і за якими обчислюємо статистики.

In [27]:
task2 = записати_вираз

Далі необхідно знайти кількість файлів за кожен місяць, їх сумарний та середній розмір, а також сумарну та середню кількість рядків. 

У результаті групування отримався об'єкт <code>DataFrameGroupBy</code> 
(<a href="https://pandas.pydata.org/docs/reference/groupby.html" target=_blank rel="noopener noreferrer">документація тут</a>).

До нього застосовний метод <code>agg</code>, що обчислює статистики (агрегатні характеристики) (<a href="https://pandas.pydata.org/docs/reference/api/pandas.api.typing.DataFrameGroupBy.agg.html#pandas.api.typing.DataFrameGroupBy.agg" target=_blank rel="noopener noreferrer">документація тут</a>).

Для стовпчика <code>cnt</code> будемо шукати суму значень (<code>sum</code>), для стовпчика <code>size</code> будемо шукати суму значень та середнє значення (<code>mean</code>), для стовпчика <code>lines</code> будемо шукати суму значень та середнє значення.

Першим параметром методу <code>agg</code> зробимо словник, що задає які статистики для яких стовпчиків слід обчислювати. Ключами словника мають бути імена стовпчиків (рядки), а значеннями списки статистик або окремі статистики (статистики також задаємо рядками-іменами)).

Результат агрегування зробимо значенням змінної <code>res2</code>.

In [28]:
res2 = записати_вираз
res2.head()

           cnt       size                lines
           sum        sum          mean    sum     mean
year mon
2021 12   9434  441018241  1.575065e+07  81180  20295.0
2022 2       8      35024  8.756000e+03      0     <NA>
     3       1       5375  5.375000e+03     93     93.0
     5    2732  239706550  1.843897e+07    170     85.0
     6    3235  218300000  2.425556e+07    352    352.0

Оскільки відбувалось групування по кільком стовпчикам та для окремих стовпчиків обчислювалось кілька характеристик, то отримали складені індекси (multindex) і рядків, і стовпчиків.

Поточний індекс стовпчиків.

In [29]:
res2.columns

MultiIndex([(  'cnt',  'sum'),
            ( 'size',  'sum'),
            ( 'size', 'mean'),
            ('lines',  'sum'),
            ('lines', 'mean')],
           )

Перейдемо до простого індексу стовпчиків.

In [30]:
res2.columns = res2.columns.to_flat_index()
res2.columns

Index([   ('cnt', 'sum'),   ('size', 'sum'),  ('size', 'mean'),
        ('lines', 'sum'), ('lines', 'mean')],
      dtype='object')

In [31]:
res2.head(3)

          (cnt, sum)  (size, sum)  (size, mean)  (lines, sum)  (lines, mean)
year mon
2021 12         9434    441018241  1.575065e+07         81180        20295.0
2022 2             8        35024  8.756000e+03             0           <NA>
     3             1         5375  5.375000e+03            93           93.0

Змінимо назви стовпчиків.

In [32]:
res2.columns=['Кількість', 'Сумарний розмір', 'Середній розмір', 'Кількість рядків', 'Середня кількість рядків',]
res2.head(3)

          Кількість  Сумарний розмір  Середній розмір  Кількість рядків  \
year mon
2021 12        9434        441018241     1.575065e+07             81180
2022 2            8            35024     8.756000e+03                 0
     3            1             5375     5.375000e+03                93

          Середня кількість рядків
year mon
2021 12                    20295.0
2022 2                        <NA>
     3                        93.0

Виразимо сумарний розмір у kb.

Для цього слід поділити значення на 1024, округлити. Додатково перетворимо на цілий тип (метод <code>astype</code> дозволяє виконувати перетворення типів, <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.astype.html" target=_blank rel="noopener noreferrer">документація тут</a>). Також не забудемо змінити підпис стовпчика.

Переходимо до кілобайтів.

In [33]:
res2['Сумарний розмір'] = записати_вираз

Змінюємо підпис стовпчиків

In [34]:
задати зміну підписів стовпчиків

In [35]:
res2.head(3)

          Кількість  Сумарний розмір, kb  Середній розмір, b  \
year mon
2021 12        9434               430682        1.575065e+07
2022 2            8                   34        8.756000e+03
     3            1                    5        5.375000e+03

          Кількість рядків  Середня кількість рядків
year mon
2021 12              81180                   20295.0
2022 2                   0                      <NA>
     3                  93                      93.0

Округлити середній розмір та середню кількість рядків, перейти до цілих значень.

In [36]:
res2.info()

<class 'pandas.DataFrame'>
MultiIndex: 42 entries, (np.int64(2021), np.int64(12)) to (np.int64(2026), np.int64(2))
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Кількість                 42 non-null     int64
 1   Сумарний розмір, kb       42 non-null     int64
 2   Середній розмір, b        42 non-null     float64
 3   Кількість рядків          42 non-null     Int64
 4   Середня кількість рядків  33 non-null     Float64
dtypes: Float64(1), Int64(1), float64(1), int64(2)
memory usage: 2.0 KB

Ось тільки тепер замінимо відсутні значення кількості рядків нулями!

Якщо б це було зроблено раніше, то середня кількість рядків була б обрахована неправильно ( на неї вплинули б нульові значення замість відсутніх).

<details>
    <summary>Підказка</summary>
    Використати метод <code>fillna</code> (<a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.fillna.html" target=_blank rel="noopener noreferrer">документація тут</a>). Оскільки відсутні дані тільки в одному стовпчику, то все просто. Тільки не забудьте, що треба перетворювати наявний датасет, а не створювати новий.
</details>

In [37]:
задати заповнення відсутніх значень нулями
res2.info()

<class 'pandas.DataFrame'>
MultiIndex: 42 entries, (np.int64(2021), np.int64(12)) to (np.int64(2026), np.int64(2))
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Кількість                 42 non-null     int64
 1   Сумарний розмір, kb       42 non-null     int64
 2   Середній розмір, b        42 non-null     float64
 3   Кількість рядків          42 non-null     Int64
 4   Середня кількість рядків  42 non-null     Float64
dtypes: Float64(1), Int64(1), float64(1), int64(2)
memory usage: 2.0 KB

Тепер можна перетворювати типи стовпчиків.

In [38]:
fname = 'Середній розмір, b'
записати перетворення для стовпчика з іменем, що задається змінною fname

fname = 'Середня кількість рядків'
записати перетворення ...

In [39]:
res2

          Кількість  Сумарний розмір, kb  Середній розмір, b  \
year mon
2021 12        9434               430682            15750651
2022 2            8                   34                8756
     3            1                    5                5375
     5         2732               234088            18438965
     6         3235               213184            24255556
     9           40                 1199              153477
     11         155                 9392              739815
     12       22164               674143            57526841
2023 2           73                26731             5474431
     4            1                   11               10940
     5         1216                76041             7786602
     6         2782               185462            27130434
     7           12                33446             8562126
     9           18                  313               80081
     10        3758               136781             9337596
     11        1898                56009             4779434
     12         818                36248             1546582
2024 1        49688               639220             9769565
     2           98                26073             5339709
     3           56                  281               35929
     4            1                    3                2708
     5          865                33559             1321690
     6           43                 1963              251202
     8            1                  498              509952
     9           60                 2616              167400
     10        5791               404342            14277455
     11         861                 5975              470672
     12           5                  168               42914
2025 1           19                  141               16036
     2          254                31836             1629996
     3       148262              5867388            44505228
     4       120731              4741291            41496423
     5         1858               270864             3748176
     6           61                 4897              557174
     7           61              2830426           222950473
     8            5                    2                2437
     9          681                69826             2234432
     10        1136                78131             2500196
     11        1956                40205             1524828
     12         321                23011              906291
2026 1        49950              1763028            13372895
     2        57208              4673873           104044480

          Кількість рядків  Середня кількість рядків
year mon
2021 12              81180                     20295
2022 2                   0                         0
     3                  93                        93
     5                 170                        85
     6                 352                       352
     9                 420                       210
     11               5226                      2613
     12              79926                     26642
2023 2                   0                         0
     4                 380                       380
     5                   9                         9
     6                   0                         0
     7                   0                         0
     9                   0                         0
     10               6820                      2273
     11               8730                      2910
     12               2461                       615
2024 1              868573                    289524
     2                   0                         0
     3                4520                      2260
     4                  53                        53
     5                5903                      1476
     6                   0                         0
     8                   0                         0
     9                2725                       908
     10              50299                     12575
     11              13819                      4606
     12                211                       106
2025 1                1801                       600
     2               11065                      3688
     3             4707841                   1569280
     4             4403387                   1467796
     5               27228                      5446
     6                2019                      1010
     7                3457                      1152
     8                   0                         0
     9               21947                      7316
     10              39730                     13243
     11              31862                      7966
     12              77363                     38682
2026 1             7662090                   1094584
     2              294211                     73553

Відсортуємо в порядку, оберненому до хронологічного. 

У даному випадку слід сортувати індекс.
Допоможе метод <code>sort_index</code> (<a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sort_index.html" target=_blank rel="noopener noreferrer">документація тут</a>).

In [40]:
res2.sort_index(ascending=[False, False], inplace=True)
res2

          Кількість  Сумарний розмір, kb  Середній розмір, b  \
year mon
2026 2        57208              4673873           104044480
     1        49950              1763028            13372895
2025 12         321                23011              906291
     11        1956                40205             1524828
     10        1136                78131             2500196
     9          681                69826             2234432
     8            5                    2                2437
     7           61              2830426           222950473
     6           61                 4897              557174
     5         1858               270864             3748176
     4       120731              4741291            41496423
     3       148262              5867388            44505228
     2          254                31836             1629996
     1           19                  141               16036
2024 12           5                  168               42914
     11         861                 5975              470672
     10        5791               404342            14277455
     9           60                 2616              167400
     8            1                  498              509952
     6           43                 1963              251202
     5          865                33559             1321690
     4            1                    3                2708
     3           56                  281               35929
     2           98                26073             5339709
     1        49688               639220             9769565
2023 12         818                36248             1546582
     11        1898                56009             4779434
     10        3758               136781             9337596
     9           18                  313               80081
     7           12                33446             8562126
     6         2782               185462            27130434
     5         1216                76041             7786602
     4            1                   11               10940
     2           73                26731             5474431
2022 12       22164               674143            57526841
     11         155                 9392              739815
     9           40                 1199              153477
     6         3235               213184            24255556
     5         2732               234088            18438965
     3            1                    5                5375
     2            8                   34                8756
2021 12        9434               430682            15750651

          Кількість рядків  Середня кількість рядків
year mon
2026 2              294211                     73553
     1             7662090                   1094584
2025 12              77363                     38682
     11              31862                      7966
     10              39730                     13243
     9               21947                      7316
     8                   0                         0
     7                3457                      1152
     6                2019                      1010
     5               27228                      5446
     4             4403387                   1467796
     3             4707841                   1569280
     2               11065                      3688
     1                1801                       600
2024 12                211                       106
     11              13819                      4606
     10              50299                     12575
     9                2725                       908
     8                   0                         0
     6                   0                         0
     5                5903                      1476
     4                  53                        53
     3                4520                      2260
     2                   0                         0
     1              868573                    289524
2023 12               2461                       615
     11               8730                      2910
     10               6820                      2273
     9                   0                         0
     7                   0                         0
     6                   0                         0
     5                   9                         9
     4                 380                       380
     2                   0                         0
2022 12              79926                     26642
     11               5226                      2613
     9                 420                       210
     6                 352                       352
     5                 170                        85
     3                  93                        93
     2                   0                         0
2021 12              81180                     20295

## Частину 2 зроблено!